### ISSUE TITLE
PR Deneme

### ISSUE THREAD

**Issue by alperyazar** [asynx-dev/www#6]
PR akışının çalıştığını test etmek için tepe dizinde `USERNAME.txt` açıp, içerisine `USERNAME` yazıp bir PR başlatabilir misiniz? `USERNAME` yerine kullanıcı adlarını yazalım. PR açabilmek için `master` dışında bir branch açıp, oraya pushlamak gerekiyor. Açtığınız PRlara beni assign edin lütfen. Bu esnada SSH key gibi şeyleri kurmadıysanız kolaylık olması açısından bakabilirsiniz onlara da:

- https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
- https://github.com/firstcontributions/first-contributions/blob/master/translations/README.tr.md

- [x] yunus
- [x] anıl

**Comment by aniltirli** [comment]
Done

**Comment by alperyazar** [comment]
Hmm, tüm issue kapanmış oysa ki sen kendi tarafını yapmıştın. Keywordü görünce kapatmış demeki ki @aniltirli

**Comment by aniltirli** [comment]
Aslında keyword olmayabilir. "Close with comment" butonuna tıklamıştım. Ondan kapatmıştır. DONE.

**Comment by alperyazar** [comment]
Anladım. Çoklu kişilerde herkesin onayı olmadan kapatmamasını beklerdim. Burada tek başına kapatabiliyor.

**Comment by alperyazar** [comment]
Teşekkürler :)
