### ISSUE TITLE
İçerik için bir lisans belirlenmesi

### ISSUE THREAD

**Issue by alperyazar** [asynx-dev/www#9]
Sitede bulunacak içerikler için bir lisans belirlememiz faydalı olacaktır. Ben kişisel sitemde **CC BY-SA 4.0** kullanıyorum. Bu lisans içeriğin ticari de olsa referans verildiği üzere kullanılmasına izin veriyor temelde. Burası için de aynı lisansı kullanabiliriz diye düşünüyorum.

Birçok ön tanımlı lisans olsa da yazılım olmayan projeler için bu işler biraz daha farklı sanırım. O yüzden bu tarz doküman işleri için lisanslar daha az ama varlar elbette.

Linkler:

- https://creativecommons.org/choose/
- https://choosealicense.com/non-software/
- https://creativecommons.org/licenses/by-sa/4.0/
- https://spdx.org/licenses/

Yapılacaklar:

- [x] Görüş topla
- [ ] Repo içerisinde ilgili `LICENSE` dosyalarını oluştur, site içeriğine de ekle
- [ ] Bir [bak](https://writing.stackexchange.com/a/27055)

**Comment by alperyazar** [comment]
@asynx-dev/www-contributors görüşlerinizi iletebilirseniz memnun olurum.

**Comment by aniltirli** [comment]
Yazacaklarım ile ilgili bende tam bir kafa yapısı oluşmadığı için lisans için de fikir yürütemiyorum. FOSS olabilir. CC BY-SA 4.0 de olabilir. Yazı bazında da olabilir belki.

**Comment by alperyazar** [comment]
> Yazacaklarım ile ilgili bende tam bir kafa yapısı oluşmadığı için lisans için de fikir yürütemiyorum. FOSS olabilir. CC BY-SA 4.0 de olabilir. Yazı bazında da olabilir belki.

Yazı bazında olması aklıma gelmemişti. Ama repo bazında bir lisans olması daha iyi olabilir. Gördüğüm uygulamalar bu şekilde, reponun bir lisansı oluyor. Bu sayede bu proje şu lisanstadır diyebiliyor Github ya da diğer toollar. Ayrıca katkıda bulunmak isteyen kişiler için de daha net oluyor. Diğer türlü şu yazılar böyle diğerleri böyle lisanslıdır dersek katkıda bulunmak isteyen biri için de benim lisans ne olacak diye bir soru işareti oluşabilir. :)

Benim bildiğim FOSS diye bir lisans yok. Şimdi tekrar düşününce biraz daha açık olmak adına CC BY 4.0 mantıklı geliyor. SA kısmını atabiliriz bence.

**Önerim CC BY 4.0.**

@yunusesergun ?

**Comment by alperyazar** [comment]
Yüz yüze görüşmeler sonucunda çıkan görüşleri de değerlendirerek CC BY 4.0 olarak gerekli düzenlemeleri yapıyorum.
